### ISSUE TITLE
strange relaunch compile error: "ghc: missing -B<dir> option"

### ISSUE THREAD

**Issue by waynr** [willdonnelly/dyre#22] opened 2014-12-26 19:44 UTC
I am simply trying Dyre out in preparation to use it in a project so I tried to run the example shown here: https://github.com/willdonnelly/dyre/blob/master/Config/Dyre.hs#L23

I am running GHC 7.6.3 installed from package on Debian 8/Jessie.

I checked out the ghc man page and did not see the `-B<dir>` option at all.

The steps to reproduce:

```
$runhaskell Main.hs
Launching custom binary ~/.cache/dyreExample/dyreExample-linux-x86_64

Dyre Example v0.1 (Modified)
> hello
ghc: missing -B<dir> option
$
```

Let me know if there is additional information I can provide.

**Comment by sboosali** [comment] 2015-01-04 18:55
btw, i found `-B` here:

    $ cat `which ghc` | grep '\-B'

**Comment by worldsayshi** [comment] 2015-02-10 22:46
I see the same problem. Compiling and running the example works but using cabal repl or runhaskell doesn't. 

Glasgow Haskell Compiler, Version 7.8.3
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library
dyre 0.8.12

**Comment by frasertweedale** [comment] 2019-12-20 04:06
I'm going to close this issue due to old age.  If you are experiencing this issue please provide fresh details as well as a clear description (e.g. in the form of a CLI transcript) of the expected behaviour.

**Closed by frasertweedale** 2019-12-20 04:06 UTC
